baseurl = "/"
title = "Razon Yang"
author = "Razon Yang"
# canonifyurls = true
paginate = 10
theme = "clarity"

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
disqusShortname = "razonyang"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    # style = "monokai"
    tabWidth = 2
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false # change to true to enable inclusion of rawHTML and math functions
    xhtml = false
