[zh]
  LanguageName = "简体中文"
  weight = 1
  languageCode = "zh_CN"
  [zh.params]
    introDescription = "PHPer、Gopher、全栈工程师"

[en]
  LanguageName = "English"
  languageCode = "en_US"
  weight = 2
  [en.params]
    introDescription = "PHPer, Gopher, Full stack engineer."
