[[main]]
  name = "项目"
  identifier = "projects"
  weight = 100
[[main]]
  parent = "projects"
  name = "CleverGo"
  url = "https://clevergo.tech/"
[[main]]
  parent = "projects"
  name = "GOPKGS"
  url = "https://gopkgs.net/"
[[main]]
  parent = "projects"
  name = "Yii 2 管理后台"
  url = "https://admin.yii2.razonyang.com/"
[[main]]
  parent = "projects"
  name = "Hugo Bootstrap 主题"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
