author = "Razon Yang"
brand = "RAZON YANG"
palette = "blue"

mainSections = ["posts"]

comment = true

recentPostCount = 10
featuredPostCount = 5

[beian]
  no = "粤公网安备44040302000341号"
  link = "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44040302000341"
  icpNo = "粤ICP备20043980号"
  icpLink = "http://beian.miit.gov.cn/"

[share]
  addThis = "ra-5fb19b4fde14befc"
