[[main]]
  name = "首页"
  url = "/"
  weight = 10

[[main]]
  name = "开发"
  url = "/categories/programing/"
  weight = 70

[[main]]
  name = "Linux"
  url = "/categories/linux/"
  weight = 80

[[main]]
  name = "项目"
  identifier = "projects"
  weight = 100
[[main]]
  parent = "projects"
  name = "CleverGo"
  url = "https://clevergo.tech/"
[[main]]
  parent = "projects"
  name = "GOPKGS"
  url = "https://gopkgs.net/"
[[main]]
  parent = "projects"
  name = "Yii 2 Admin"
  url = "https://admin.yii2.razonyang.com/"
